### PR TITLE
WIP: bugfix for summary statistics

### PR DESCRIPTION
**Pull request by Marigold**

### CODE REVIEW

**Comment by ludovicc** [comment]
@Marigold can you add to the summary statistics results the number of null values?

**Comment by Marigold** [comment]
Added number of null values to summary statistics.

@ludovicc where do I find statistics schema required by frontend? I've added some fields (and modified some, please see questions in https://github.com/LREN-CHUV/algorithm-repository/pull/7) and I'm worried it might break things in production. Existing output looks [like this](https://github.com/LREN-CHUV/algorithm-repository/pull/12/files#diff-9c5ea4c198d2c2d3c107c14c2110110aR121).

**Comment by ludovicc** [comment]
@Marigold can you update this PR: mip_helper is now at version 0.3.1 and includes your latest changes, the hack for local mip_helper should be removed, also can you copy from python-histograms the execution of unit tests from Dockerfile.

**Comment by Marigold** [comment]
Done, added unit tests prior to building the dockerfile here https://github.com/LREN-CHUV/algorithm-repository/pull/12/files#diff-a13f8804ca87de6f8e5c1ea3027cd270R1 and upgraded `python-mip` everywhere.

**Pull request merged**
