### PR TITLE
Distributed linear regression

### PR DESCRIPTION
**Pull request by Marigold**
~~The output is different from previous version - the original JSON with coefficients is moved into `summary` field (in order to be able to return more information used by distributed mode). Here's an example https://github.com/LREN-CHUV/algorithm-repository/compare/master...Marigold:distributed-linear-regression?expand=1#diff-4113d9273636ba13619cab2f5b2e5ca6R10~~

Would it be possible to change woken to use `summary` field now? Alternative I can keep the original format and only use new format in distributed mode.

Also please see https://github.com/LREN-CHUV/algorithm-repository/compare/master...Marigold:distributed-linear-regression?expand=1#diff-4113d9273636ba13619cab2f5b2e5ca6R50 that explains why p-values from distributed mode differ from a single-node case. This could be fixed, but it would require two iterations over all nodes instead of one.

### CODE REVIEW

**Comment by ludovicc** [comment]
@Marigold Can you return a PFA document for both single mode and distributed mode results? We had that for the R implementation, I don't know why this was lost. You can find some samples here: https://github.com/LREN-CHUV/algorithm-repository/blob/master/r-linear-regression/docs/samples/feature_tissuevolume_pfa.yml 
https://github.com/LREN-CHUV/algorithm-repository/blob/master/r-linear-regression/docs/samples/length_conc_strip_pfa.yml

(please ignore the Anova results)

I think that we should keep the current output, which is easy for the web front-end to display. Currently, Woken does not support well multiple outputs, but this is a capacity I want to add. So here you would store 2 results, one in Json tabular data format, another in PFA format.

PFA can then be used to do cross-validation and benchmarking of the model.

**Comment by Marigold** [comment]
Does the PFA have to be as sleek as the R implementation (including all the summaries and residuals that will be returned in JSON anyway) or can it be simple like the ones I'm generating by `sklearn_to_pfa` package?

> Can you return a PFA document for both single mode and distributed mode results?

Ok, so I'll keep the results format for single mode and distributed mode and add PFA for both.

**Comment by ludovicc** [comment]
Yes, the PFA should include the model with its coefficients and the summary with residuals, coefficients including t- and p-values, R square and whatever else is useful and returned today in the Json.

I want that all predictive models are fully documented and explained by looking only at their PFA representation. You can ignore for example the query (https://github.com/LREN-CHUV/algorithm-repository/blob/master/r-linear-regression/docs/samples/feature_tissuevolume_pfa.yml#L22), this information can be added post-execution by Woken as it knows everything to track provenance.

**Comment by Marigold** [comment]
The model is now returning coefficients in the original format again (both single and distributed mode) and also generates PFA with regression model, but that is not saved anywhere yet (it's waiting for woken's support of multiple outputs). It also doesn't contain summary stats yet.

What I'm struggling with are one-hot encoded nominal variables in linear regression. The problems is that if I include all categories as columns with 0/1, the feature matrix will be singular and regression coefficients for categorical variables would not be unique. One way around this is eliminating redundant columns (that is what R and statsmodels do), but that always gets impractical if you want to make predictions (with PFA). Another way is to use regularised linear regression, which is IMHO better in all aspects (the only disadvantage is that calculation of p-values gets a bit trickier). I haven't made my mind yet what to use, so if you have an opinion about this, I'm all ears. Thanks!

**Comment by Marigold** [comment]
I've decided to remove linearly dependent columns to stay consistent with the previous approach.

**Comment by Marigold** [comment]
@ludovicc could you review this PR please? its output is consistent with current python-linear-regression, but it also supports distributed mode and has better error handling. I could rebase logistic regression on top of this then

**Comment by ludovicc** [comment]
@Marigold @Fkherif may be able to answer your question about one-hot encoded nominal variables

**Comment by Marigold** [comment]
@Fkherif that would be great. Please see [this comment](https://github.com/LREN-CHUV/algorithm-repository/pull/33#issuecomment-382493423). The question is whether to remove redundant features that are linearly dependent (one-hot encoding of categoricals) or to use regulatization. Removing redundant features could be confusing for the user (see [Trello discussion](https://trello.com/c/HimLjWLS/96-error-in-the-output-of-a-linear-regression-experiment-for-the-uat-case-1)), on the other hand regularization makes the math a bit trickier and is not fully implemented in statsmodels.

**Pull request merged**
